[package]
name        = "badge-hub"
version     = "1.0.0"
authors     = ["larry <gm@larry.engineer>"]
edition     = "2021"
description = "Badge Hub contract is where event organizers create, mint, or edit badges."
readme      = "README.md"
homepage    = "https://badges.fun"
repository  = "https://github.com/steak-enjoyers/badges"
license     = "GPL-3.0-or-later"
keywords    = ["nft", "cosmos", "cosmwasm", "stargaze"]

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[features]
library = []

[dependencies]
badges = { path = "../../packages/badges" }
cosmwasm-std = "1.0"
cw-item-set = "0.4"
cw-storage-plus = "0.13"
cw-utils = "0.13"
cw2 = "0.13"
hex = "0.4"
serde = { version = "1.0", default-features = false }
sg1 = "0.14"
sg721 = "0.14"
# TODO: update once published on crates.io
sg-metadata = { git = "https://github.com/public-awesome/launchpad", rev = "4183957" }
sg-std = "0.14"
sha2 = "0.10"
thiserror = "1"

[dev-dependencies]
cosmwasm-schema = "1.0"
# can't use the latest v0.11; has version conflicts of the ecdsa package
k256 = "0.10"
rand = "0.8"
